version: "3.9"

services:

  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  tidb:
    image: pingcap/tidb:v7.1.0
    ports:
      - "4000:4000"

